[package]
name = "crypto-ecosystems"
version = "0.1.0"
authors = ["Curtis Spencer"]
edition = "2018"

[dependencies]
toml = "0.4"
glob = "0.3.0"
failure = "0.1.3"
serde = { version = "1.0", features = ["derive"] }
quicli = "0.4"
structopt = "0.2"
